### ISSUE TITLE
Examples are using Gorilla mux which is now an archived project

### ISSUE THREAD

**Issue by Pawda** [PacktPublishing/Domain-Driven-Design-with-GoLang#1]
Hi @MatthewJamesBoyle,

First of all, thank you for the great book, heard about it from changelog and I'm not disappointed so far !
While reading the code examples, I see gorilla mux is used. While I think it's a great package, it's now archived and not maintained anymore. It would be better if the examples could be rewritten with a maintained library like go-chi or even better, as the examples are simple enough, stick to the stdlib.

Cheers,

**Comment by MatthewJamesBoyle** [comment]
HI @Pawda ,
Thanks for the feedback. When I was writing the book, mux was not archived. I will speak to the publisher about a second edition where we can update the examples.

Thanks for reading!
